services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 2552
    expose:
      - 2552
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 7330:8000
    depends_on:
      - db
